### ISSUE TITLE
Need to polyfill ES6 so demos work on IE11

### ISSUE THREAD

**Issue by cmulders** [Leaflet/prosthetic-hand#1]
Unfortunately the demo page does not work in IE 11. During page load (both map-pan as map-zoom) I get the error in the debugger of IE: 
`SCRIPT438: Object doesn't support property or method 'assign'
File: prosthetic-hand.js, Line: 612, Column: 8`

This error shows when the debugger is open during page load otherwise the page seems to load, while the map does not (stays gray as in screenshot).

Screenshot: 
![ie](https://cloud.githubusercontent.com/assets/8112493/13488825/d707f512-e123-11e5-81c4-d03d1ce9114f.png)

Maybe linked to: http://stackoverflow.com/a/14003088 ?
Otherwise, the issue is located in a Babel helper, maybe some (compatibility)issue over there?

Browser: IE 11
OS: Windows 7
Desktop computer, only mouse input, no touch screen/device

Hope this information helps!

**Comment by cmulders** [comment]
Aha, just IE 11 being stupid and me being to quick to not google it. Object.assign is just not supported -_-... 

http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign
https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

Babel should be able to polyfill this problem in IE :+1:

https://babeljs.io/docs/plugins/transform-object-assign/

**Comment by IvanSanchez** [comment]
Yeah, I haven't really tried IE11 - I jumped straight into my Win10+Edge VM. If you know the magic bits to make `gobble-babel` work with the babel polyfill for `Object.assign`, please be my guest and submit a PR.

**Comment by cmulders** [comment]
Unfortunately I do not currently, but should be able to figure it out. Feel free to fix yourself, if you can do it quickly, but I can imagine that your focus is currently not IE11. First you should focus to implement this lib in the Leaflet unit tests :)

Lastly, great work!

**Comment by IvanSanchez** [comment]
@cmulders Can you please check if the changes I made in df9171a fix the problem?

**Comment by cmulders** [comment]
I will, but as I am currently unable to build (no dev machine right now), could you update the gh-pages branch with the new build?

**Comment by cmulders** [comment]
Thanks! 

The map loads now, however, the buttons are now giving errors..

SCRIPT5009: 'Symbol' is undefined
File: prosthetic-hand.js, Line: 806, Column: 17

Yet more polyfills for IE11... 
http://stackoverflow.com/questions/33828840/symbol-is-undefined-in-ie-after-using-babel
https://babeljs.io/docs/usage/polyfill/
https://github.com/babel/babel-loader/issues/92#issuecomment-155863617

**Comment by IvanSanchez** [comment]
@cmulders _sigh_

Let's try again after 4fcb444bfedcdf2fa1e1bdc641e9e20f862d75e3 - removing the ES6 `for ... of ...` loops should prevent IE from seeing any `Symbol` in the code.

I've updated the demo files in `gh-pages`.

**Comment by cmulders** [comment]
Okay just drop IE before Edge
It's complicated as the DOM L4 event constructor pattern is not supported.

The console gives:

``` javascript
typeof window.Event == "function" -> false
```

while:

``` javascript
document.createEvent("MouseEvents"); -> [object MouseEvent]
```

https://msdn.microsoft.com/en-us/library/dn905219(v=vs.85).aspx

IE <= 11 requires a lot of work. :-1:

**Comment by IvanSanchez** [comment]
@cmulders Yeah, IE is full of this kind of "surprises" :-( :-1: 

I don't think it's very hard - with a bit of luck, #2 will fix everything.
