### ISSUE TITLE
Moving finger outside the element doesn't trigger `touchmove` and `touchend` events

### ISSUE THREAD

**Issue by Invis1ble** [Leaflet/prosthetic-hand#12]
After `finger.down()` called on the element coords the `touchmove` (`finger.moveBy()`) and `touchend` (`finger.up()`) events does not trigger if finger leaves the element boundaries.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by Invis1ble** [comment]
Here is a demo https://jsfiddle.net/59m29ou8/
Open console and run script (in Chrome): you should see the list of events and there are no `touchmove` and `touchend` after finger left the element. Then try to switch to touchscreen device with Chrome emulation mode and drag the element. You should see the expected list of the events.

Also, I found this: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent

> **touchend**
> 
> ...
> 
> The event's target is the same element that received the touchstart event corresponding to the touch point, **even if the touch point has moved outside that element**.
> 
> **touchmove**
> 
> Sent when the user moves a touch point along the surface. The event's target is the same element that received the touchstart event corresponding to the touch point, **even if the touch point has moved outside that element**.

**Comment by jonkoops** [comment]
We're removing all emulated events aside from Pointer Events for v2, so this issue is no longer relevant.
