### ISSUE TITLE
New eventMode 'touch+pointer' (to match real browsers behavior)

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/prosthetic-hand#14]
Checked both desktop and Android.

See https://leaflet.github.io/prosthetic-hand/demos/

Some observations:
- there is no such problem with Firefox
- there is no problem with pointer events simulation (see demos)
- there is no issue if https://github.com/Leaflet/Leaflet/pull/7029 applied

**Comment by johnd0e** [comment]
> * there is no such problem with Firefox

Addition:
```
dom.w3c_pointer_events.enabled: true
dom.w3c_touch_events.enabled: 1
```
When both touch and pointer are enabled - same problem is observed in Firefox too

**Comment by johnd0e** [comment]
The root of the issue: Leaflet remaps touch events to pointer events, and then ignores original touch events.
There is no problem in real browsers because they have both events types, and every touch is followed by relevant pointer event.

So I propose to introduce new complex `eventMode` like `touch+pointer`, to match real browsers behavior.

**Comment by jonkoops** [comment]
Since we will be removing support for anything but Pointer Events in v2 (both `prosthetic-hand` and Leaflet), I am closing this issue.
