### ISSUE TITLE
Fallback to initMouseEvent et al

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/prosthetic-hand#2]
According to https://github.com/IvanSanchez/prosthetic-hand/issues/1#issuecomment-191729192, some versions of IE will throw an error when trying to instantiate a new synthetic event via `var foo = new MouseEvent(...)`.

The way around this is to call [`initMouseEvent(...)`](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent) in that case. It's ugly, it's deprecated, but IE won't function without it.

Same goes for [`initPointerEvent`](https://msdn.microsoft.com/en-us/library/hh772109%28v=vs.85%29.aspx) in IE10/IE11.

The modifications should be simple, as they only affect code in `Finger._asPointerEvent()` and `Finger._asMouseEvent()`

**Comment by IvanSanchez** [comment]
Fixed partially in 1.1.2 but for PhantomJS. Testing in IE10/IE11 is still needed

**Comment by jonkoops** [comment]
This is no longer relevant as we do not intend to support Internet Explorer or PhantomJS going forward.
