### ISSUE TITLE
Make me a maintainer

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/prosthetic-hand#35]
Hey @IvanSanchez @mourner, I'd like to help out with this library as well. Could you guys add me as a maintainer? Thanks!

**Comment by mourner** [comment]
👍

**Comment by mourner** [comment]
@jonkoops can you share your NPM handle too?

**Comment by jonkoops** [comment]
@mourner sure it's [`jkoops`](https://www.npmjs.com/~jkoops)

**Comment by mourner** [comment]
@jonkoops 👍 added you as NPM owner for both `leaflet` (just in case) and `prosthetic-hand`.
